fix: Set correct SDK version in the Game Bridge  (#2051)

diff --git a/.github/workflows/build-game-bridge.yaml b/.github/workflows/build-game-bridge.yaml
--- a/.github/workflows/build-game-bridge.yaml
+++ b/.github/workflows/build-game-bridge.yaml
@@ -31,7 +31,7 @@ env:
   DRY_RUN: ${{ github.event.inputs.dry_run }}
   GH_TOKEN: ${{ secrets.TS_IMMUTABLE_SDK_GITHUB_TOKEN }}
   SDK_TEAM_MEMBERS: ${{ secrets.SDK_TEAM_MEMBERS }}
-  CI: ${{ github.env.CI }}
+  CI: true
 
 jobs:
   build-game-bridge:
@@ -66,6 +66,26 @@ jobs:
 
       - name: Build Game Bridge
         run: yarn nx run @imtbl/game-bridge:build --skip-nx-cache
+
+      - name: Check Unity Version String Updated
+        if: ${{ github.event.inputs.game_engine == 'Unity' || github.event.inputs.game_engine == 'Both' }}
+        run: |
+          UNITY_ARTIFACT_PATH="./packages/game-bridge/dist/unity/index.html"
+          UNITY_VERSION_STRING_COUNT=$(cat $UNITY_ARTIFACT_PATH | grep -c -o "ts-immutable-sdk-${{ env.TS_SDK_TAG }}")
+          if [ "$UNITY_VERSION_STRING_COUNT" -eq 0 ]; then
+              echo "Error: Updated version string not found in $UNITY_ARTIFACT_PATH"
+              exit 1
+          fi
+
+      - name: Check Unreal Version String Updated
+        if: ${{ github.event.inputs.game_engine == 'Unreal' || github.event.inputs.game_engine == 'Both' }}
+        run: |
+          UNREAL_ARTIFACT_PATH="./packages/game-bridge/dist/unreal/index.js"
+          UNREAL_VERSION_STRING_COUNT=$(cat $UNREAL_ARTIFACT_PATH | grep -c -o "ts-immutable-sdk-${{ env.TS_SDK_TAG }}")
+          if [ "$UNREAL_VERSION_STRING_COUNT" -eq 0 ]; then
+              echo "Error: Updated version string not found in $UNREAL_ARTIFACT_PATH"
+              exit 1
+          fi
 
       - name: Cache build artifacts
         uses: actions/cache@v4
