refactor: use version.json for autoupdating & remove dependency on npm registry for checking for latest version (#2471)

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -94,6 +94,11 @@ jobs:
         id: version
         run: |
           echo "NEXT_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
+          
+      - name: Generate version.json
+        run: |
+          echo '{ "version": "${{ steps.version.outputs.NEXT_VERSION }}" }' > ./sdk/version.json
+          cp ./sdk/version.json ./sdk/dist/
 
       - name: Typecheck
         run: yarn typecheck
@@ -129,12 +134,6 @@ jobs:
           package: ./sdk/package.json
           tag: ${{ contains(env.RELEASE_TYPE, 'alpha') && 'alpha' }}
           dry-run: ${{ env.DRY_RUN }}
-
-      - name: Generate last_updated.json
-        if: (env.DRY_RUN) == 'false'
-        run: |
-          echo "{\"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" > ./sdk/last_updated.json
-          cp ./sdk/last_updated.json ./sdk/dist/
 
       # ! Do NOT remove - this will cause a Sev 0 incident !
       - name: Generate SDK attestation
@@ -186,3 +185,30 @@ jobs:
         uses: ./.github/actions/notify-slack-publish-status
         with:
           message: "❌ Failed to publish SDK version ${{steps.version.outputs.NEXT_VERSION}} to NPM. ${{ github.triggering_actor }} please check the logs for more details."
+
+    - name: Wait for NPM @latest Update
+        id: wait_for_npm_update
+        if: contains(env.RELEASE_TYPE, 'release') && env.DRY_RUN == 'false'
+        run: |
+          VERSION="${{ steps.version.outputs.NEXT_VERSION }}"
+          echo "Waiting for NPM registry to reflect version: $VERSION"
+
+          for i in {1..20}; do
+            LATEST_VERSION=$(npm view @imtbl/sdk@latest version)
+            if [[ "$LATEST_VERSION" == "$VERSION" ]]; then
+              echo "NPM registry updated to version: $LATEST_VERSION"
+              exit 0
+            fi
+            echo "NPM registry not updated yet, retrying in 15 seconds..."
+            sleep 15
+          done
+
+          echo "NPM registry failed to update after 5 minutes."
+          exit 1
+
+      - name: Purge CDN Cache for version.json
+        id: purge_cdn
+        if: contains(env.RELEASE_TYPE, 'release') && env.DRY_RUN == 'false'
+        run: |
+          curl -X GET https://purge.jsdelivr.net/npm/@imtbl/sdk@latest/dist/version.json
+          echo "CDN cache purged for https://cdn.jsdelivr.net/npm/@imtbl/sdk@latest/dist/version.json"
